version: "2"
services:
  hugo:
    image: klakegg/hugo:0.88.0-ext
    working_dir: /app
    entrypoint: "hugo"
    command: ["server", "--bind", "0.0.0.0"]
    ports:
      - 1313:1313
    volumes:
      - .:/app
